version: '3'
services:
  scheduler:
    network_mode: host
    build: scheduler
    volumes:
      # https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scheduler/flows:/root/.prefect/flows/
    ports:
      - 3001
      - 4001
      - 8080
