[tool.poetry]
name = "scheduler"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.7.9"
invoke = "^1.4.1"
pexpect = "^4.8.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
